//this file is going to allow us to set rules for the auth layout
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
// import './globals.css'

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });


//this is the metadata for the SEO 
export const metadata: Metadata = {
    title: "Auth",
    description: "Generated by create next app",
};



export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        //wrap the children in the ClerkProvider for the auth functionalities 
        <ClerkProvider
            appearance={{
                // baseTheme: dark,
            }}
        >
            {/* //set the language and the body class */}
            <html lang='en'>
                {/* //set the language and the body class */}
                <body className={`${inter.className}
                `}>
                    {children}</body>
            </html>
        </ClerkProvider>
    );
}
